#!/usr/bin/env ruby

site 'http://community.opscode.com/api/v1'

cookbook 'ubuntu', '1.1.6'
cookbook 'locale', '0.0.2'
cookbook 'cron', '1.3.10'
cookbook 'openssl', '1.1.0'
cookbook 'logrotate', '1.5.0'
cookbook 'apache2', '1.10.2'
cookbook 'php', '1.4.6'
cookbook 'mysql', '5.1.8'
cookbook 'sqlite', '1.0.0'
cookbook 'memcached', '1.7.2'
cookbook 'imagemagick', '0.2.3'
