#!/usr/bin/env ruby

site 'http://community.opscode.com/api/v1'

cookbook 'locale', '1.0.2'
cookbook 'cron', '1.4.0'
cookbook 'openssl', '2.0.0'
cookbook 'php', '1.4.6'
cookbook 'mysql', '5.3.6'
cookbook 'sqlite', '1.1.0'
cookbook 'memcached', '1.7.2'
cookbook 'imagemagick', '0.2.3'
cookbook 'postfix', '3.4.0'
cookbook 'dovecot', '1.0.0'
cookbook 'apache2', '2.0.0'
