#!/usr/bin/env ruby

site 'http://community.opscode.com/api/v1'

cookbook 'ubuntu', '1.1.6'
cookbook 'locale', '0.0.2'
cookbook 'cron', '1.4.0'
cookbook 'openssl', '2.0.0'
cookbook 'php', '1.4.6'
cookbook 'mysql', '5.3.6'
cookbook 'sqlite', '1.0.0'
cookbook 'memcached', '1.7.2'
cookbook 'imagemagick', '0.2.3'

cookbook 'apache2',
  :git => 'https://github.com/onehealth-cookbooks/apache2.git',
  :ref => 'COOK-3900'
